import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar configuration for the book
  bookSidebar: [
    'chapters/intro',
    {
      type: 'category',
      label: 'Module 1: ROS 2 Fundamentals',
      items: [
        'chapters/module-1/index',
        {
          type: 'category',
          label: 'Chapter 1: Introduction to ROS 2',
          items: [
            'chapters/module-1/chapter-1/index',
            'chapters/module-1/chapter-1/lesson-1',
            'chapters/module-1/chapter-1/lesson-2',
            'chapters/module-1/chapter-1/lesson-3'
          ]
        },
        {
          type: 'category',
          label: 'Chapter 2: Python Control with rclpy',
          items: [
            'chapters/module-1/chapter-2/index',
            'chapters/module-1/chapter-2/lesson-1',
            'chapters/module-1/chapter-2/lesson-2',
            'chapters/module-1/chapter-2/lesson-3'
          ]
        },
        {
          type: 'category',
          label: 'Chapter 3: Humanoid Modeling with URDF',
          items: [
            'chapters/module-1/chapter-3/index',
            'chapters/module-1/chapter-3/lesson-1',
            'chapters/module-1/chapter-3/lesson-2',
            'chapters/module-1/chapter-3/lesson-3'
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Module 2: Simulation Environments',
      items: [
        'chapters/module-2/index',
        {
          type: 'category',
          label: 'Chapter 1: Physics Simulation with Gazebo',
          items: [
            'chapters/module-2/chapter-1/index'
          ]
        },
        {
          type: 'category',
          label: 'Chapter 2: Environment & Interaction Design',
          items: [
            'chapters/module-2/chapter-2/index'
          ]
        },
        {
          type: 'category',
          label: 'Chapter 3: Sensor Simulation',
          items: [
            'chapters/module-2/chapter-3/index'
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Module 3: Isaac AI Framework',
      items: [
        'chapters/module-3/index',
        {
          type: 'category',
          label: 'Chapter 1: Isaac Overview',
          items: [
            'chapters/module-3/chapter-1/index'
          ]
        },
        {
          type: 'category',
          label: 'Chapter 2: Perception Systems',
          items: [
            'chapters/module-3/chapter-2/index'
          ]
        },
        {
          type: 'category',
          label: 'Chapter 3: Control Systems',
          items: [
            'chapters/module-3/chapter-3/index'
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Module 4: Vision Language Action (VLA) Models',
      items: [
        'chapters/module-4/index',
        {
          type: 'category',
          label: 'Chapter 1: VLA Fundamentals',
          items: [
            'chapters/module-4/chapter-1/index'
          ]
        },
        {
          type: 'category',
          label: 'Chapter 2: Multimodal Integration',
          items: [
            'chapters/module-4/chapter-2/index'
          ]
        },
        {
          type: 'category',
          label: 'Chapter 3: Humanoid Applications',
          items: [
            'chapters/module-4/chapter-3/index'
          ]
        }
      ]
    }
  ]
};

export default sidebars;
